# pyproject.toml
[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"] # Optional: Add any other ignores you might need
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    "build",
    "dist",
]