"""Initial migration with all tables

Revision ID: 7d0a34e5d3f4
Revises: 241610651eae
Create Date: 2025-08-17 15:56:30.016635

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7d0a34e5d3f4"
down_revision: Union[str, Sequence[str], None] = "241610651eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
