"""Initial migration

Revision ID: 53d85615b656
Revises: 
Create Date: 2025-08-16 09:59:36.086556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d85615b656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_provider_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('cloudflare', 'digitalocean', name='dnsprovidertype'), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('managed_domain', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_domain', 'company', name='dns_provider_managed_domain_company_unique')
    )
    op.create_index(op.f('ix_dns_provider_accounts_id'), 'dns_provider_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_dns_provider_accounts_managed_domain'), 'dns_provider_accounts', ['managed_domain'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('target_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=True),
    sa.Column('system_type', sa.Enum('fortigate', 'panos', 'sonicwall', 'iis', 'azure', name='targetsystemtype'), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('public_ip', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('admin_password', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_name', 'system_type', name='target_systems_system_name_type_unique')
    )
    op.create_index(op.f('ix_target_systems_id'), 'target_systems', ['id'], unique=False)
    op.create_index(op.f('ix_target_systems_system_name'), 'target_systems', ['system_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'technician', 'readonly', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_body', sa.Text(), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('pfx_path', sa.String(), nullable=True),
    sa.Column('dns_provider_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dns_provider_account_id'], ['dns_provider_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_name', name='certificates_common_name_unique')
    )
    op.create_index(op.f('ix_certificates_common_name'), 'certificates', ['common_name'], unique=True)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('target_system_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='deploymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('auto_renewal_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('deployment_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['target_system_id'], ['target_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_common_name'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_target_systems_system_name'), table_name='target_systems')
    op.drop_index(op.f('ix_target_systems_id'), table_name='target_systems')
    op.drop_table('target_systems')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_dns_provider_accounts_managed_domain'), table_name='dns_provider_accounts')
    op.drop_index(op.f('ix_dns_provider_accounts_id'), table_name='dns_provider_accounts')
    op.drop_table('dns_provider_accounts')
    # ### end Alembic commands ###
